const {
  VITE_FIREBASE_API_KEY: FIREBASE_API_KEY,
  VITE_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  VITE_FIREBASE_PROJECTID: FIREBASE_PROJECTID,
  VITE_FIREBASE_STORAGEBUCKET: FIREBASE_STORAGEBUCKET,
  VITE_FIREBASE_MESSAGINGSENDERID: FIREBASE_MESSAGINGSENDERID,
  VITE_FIREBASE_APPID: FIREBASE_APPID,
} = import.meta.env;

export { FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECTID, FIREBASE_STORAGEBUCKET, FIREBASE_MESSAGINGSENDERID, FIREBASE_APPID };